# Generated by Django 2.0 on 2018-05-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogbody', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.CharField(default='f', max_length=200),
            preserve_default=False,
        ),
    ]
