# Generated by Django 2.0 on 2018-05-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogbody', '0002_post_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='banner',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='blogbody.Tag'),
        ),
    ]
